load("@rules_cc//cc:defs.bzl", "cc_library", "objc_library")

cc_library(
    name = "ui",
    srcs = [
        "Panels/ConsolePanel.cpp",
        "Panels/DecompilerViewerPanel.cpp",
        "Panels/DisassemblyViewerPanel.cpp",
        "Panels/FunctionListingPanel.cpp",
        "Panels/HexViewerPanel.cpp",
        "Panels/GraphViewPanel.cpp",
        "Components/ThirdPartyTextRenderer.cpp",
        "Components/SettingsWidget.cpp",
    ],
    hdrs = [
        "Panels/ConsolePanel.h",
        "Panels/ConsoleSink.h",
        "Panels/DecompilerViewerPanel.h",
        "Panels/DisassemblyViewerPanel.h",
        "Panels/FunctionListingPanel.h",
        "Panels/HexViewerPanel.h",
        "Panels/GraphViewPanel.h",
        "Panels/IPanel.h",
        "Panels/PanelManager.h",
        "Components/ITextRenderer.h",
        "Components/ThirdPartyTextRenderer.h",
        "Components/SettingsWidget.h",
    ],
    visibility = [
        "//:__pkg__",
        "//TitaniumApplication/src:__subpackages__",
    ],
    copts = [
        "-ITitaniumDecompiler/src",
        "-ITitaniumLogger/src",
        "-ITitaniumRenderer/src"
    ],
    deps = [
        "@imguilib//:imgui",
        "//TitaniumApplication/src/Core:core",
        "//TitaniumLogger/src/TitaniumLogger/Logger:titanium_logger",
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumRenderer/src/TitaniumRenderer/UI:ui",
        "//TitaniumRenderer/src:TitaniumRenderer",
    ],
    linkstatic = 1,
)
