cc_library(
    name = "titanium_renderer_core",
    srcs = [
        "Application.cpp",
        "Layer.cpp",
        "LayerStack.cpp",
        "Window.cpp",
    ],
    copts = [
        "-ITitaniumRenderer/src",
    ],
    linkstatic = 1,
    # strip_include_prefix = "//TitaniumRenderer/src",
    visibility = [
        "//TitaniumRenderer/src:__subpackages__",
    ],
    deps = [
        ":headers",
        "//TitaniumLogger/src:TitaniumLogger",
        "//TitaniumRenderer/src/TitaniumRenderer/ImGui:titanium_renderer_imgui",
        "//TitaniumRenderer/src/TitaniumRenderer/Renderer:renderer_internals",
        "@spdloglib//:spdlog",
    ] + select({
        "@platforms//os:macos": [
            "//TitaniumRenderer/src/Platform/Mac:titanium_renderer_platform_mac",
        ],
        "//conditions:default": [
            "//TitaniumRenderer/src/Platform/Windows:titanium_renderer_platform_windows",
        ],
    }),
)

cc_library(
    name = "headers",
    hdrs = [
        "Application.h",
        "Assert.h",
        "Base.h",
        "EntryPoint.h",
        "Input.h",
        "KeyCodes.h",
        "Layer.h",
        "LayerStack.h",
        "MouseCodes.h",
        "PlatformDetection.h",
        "Timestep.h",
        "Window.h",
    ],
    copts = [
        "-ITitaniumRenderer/src",
    ],
    # strip_include_prefix = "//TitaniumRenderer/src",
    visibility = [
        "//TitaniumRenderer/src:__pkg__",
        "//TitaniumRenderer/src:__subpackages__",
    ],
    deps = [
        "//TitaniumRenderer/src/TitaniumRenderer/Events:titanium_renderer_events",
        "//TitaniumRenderer/src/TitaniumRenderer/ImGui:headers",
    ],
)
