load("@rules_cc//cc:defs.bzl", "cc_library", "objc_library")

cc_library(
    name = "cfg",
    srcs = [
        "CFGBuilder.cpp",
    ],
    hdrs = [
        "CFG.h",
        "CFGBuilder.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//TitaniumDecompiler/src/Core:core",
        "//TitaniumDecompiler/src/Core/Disassembly:disassembly",
    ],
)
