cc_library(
    name = "titanium_renderer_platform_metal",
    srcs = [
        "MetalContext.cpp",
        "MetalImGuiRenderer.cpp",
        "MetalRendererAPI.cpp",
    ],
    copts = [
        "-ITitaniumRenderer/src",
        "-ITitaniumLogger/src",
    ],
    defines = [
        "GLFW_INCLUDE_NONE",
    ],
    linkopts = [
        "-framework Metal",
        "-framework Foundation",
    ],
    # strip_include_prefix = "//TitaniumRenderer/src",
    visibility = [
        "//TitaniumRenderer/src:__subpackages__",
    ],
    deps = [
        ":headers",
        "//TitaniumLogger/src/TitaniumLogger/Logger:titanium_logger",
        "//TitaniumRenderer/src/TitaniumRenderer/Core:headers",
        "//TitaniumRenderer/src/TitaniumRenderer/Renderer:headers",
        "@GLFW//:glfw",
        "@Metal//:metal",
        "@imguilib//:imgui",
        "@spdloglib//:spdlog",
    ],
)

cc_library(
    name = "headers",
    hdrs = [
        "MetalContext.h",
        "MetalImGuiRenderer.h",
        "MetalRendererAPI.h",
    ],
    copts = [
        "-ITitaniumRenderer/src",
    ],
    # strip_include_prefix = "//TitaniumRenderer/src",
    visibility = [
        "//TitaniumRenderer/src:__subpackages__",
    ],
    deps = [
        # "//TitaniumRenderer/src/TitaniumRenderer/Core:headers",
        # "//TitaniumRenderer/src/TitaniumRenderer/Renderer:headers",
    ],
)
