;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                 HexRays                                 |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : CA827579527BFBCFB6E65A77FDD8C4A4FEECBD42601B30066AD251AD0D628358
; Input MD5    : F4924C15A2662121C5EE5D918E6ACD1E
; Input CRC32  : 98258FC0

; File Name   : /home/austin/Github/Decompiler-Kotlin/JavaTestFiles/TestInvokeDynamic.class
; Format      : JavaVM Class File (JDK 1.8)

;Java Virtual Machine (JDK 1.8)

.bytecode 52.0
.source "TestInvokeDynamic.java"
;BootstrapMethods : 1
java.lang.invoke.LambdaMetafactory.metafactory(java.lang.invoke.MethodHandles$Lookup, java.lang.String, java.lang.invoke.MethodType, java.lang.invoke.MethodType, java.lang.invoke.MethodHandle, java.lang.invoke.MethodType)java.lang.                invoke.CallSite

Argument #0:                 (java.lang.Object)void

Argument #1:                 java.io.PrintStream.println(java.lang.String)void

Argument #2:                 (java.lang.String)void


; ---------------------------------------------------------------------------


; Importing prototypes

;.import java.lang.Object                      ; DATA XREF: TestInvokeDynamic↓i
;  java.lang.Object.<init>()void               ; CODE XREF: <init>+1↓P
;  java.lang.Object.getClass()java.lang.Class  ; CODE XREF: main+4↓P
;.import java.lang.System
;  java.lang.System.out java.io.PrintStream    ; DATA XREF: main↓r
;.import java.util.function.Consumer
;  java.util.function.Consumer.accept(java.lang.Object)void ; CODE XREF: main+17↓P
;.import java.lang.invoke.LambdaMetafactory
;  java.lang.invoke.LambdaMetafactory.metafactory(java.lang.invoke.MethodHandles$Lookup, java.lang.String, java.lang.invoke.MethodType, java.lang.invoke.MethodType, java.lang.invoke.MethodHandle, java.lang.invoke.MethodType)java.lang.invoke.CallSite
;.import java.io.PrintStream
;  java.io.PrintStream.println(java.lang.String)void
;.import java.lang.invoke.MethodHandles$Lookup
;.import java.lang.invoke.MethodHandles

; ---------------------------------------------------------------------------


.class public TestInvokeDynamic
.super java.lang.Object

  .inner class public static final Lookup inner java.lang.invoke.MethodHandles$Lookup outer java.lang.invoke.MethodHandles

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public <init>
  .limit stack 1
  .limit locals 1
  .line 3
    aload_0 ; met001_slot000
    invokespecial java.lang.Object.<init>()void
    return


;met001_slot000                                ; DATA XREF: <init>↑r
  .end method

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public static main
  .limit stack 2
  .limit locals 2
  .line 6
    getstatic java.lang.System.out java.io.PrintStream
    dup
    invokevirtual java.lang.Object.getClass()java.lang.Class
    pop
    invokedynamic accept(java.io.PrintStream)java.util.function.Consumer
    astore_1 ; met002_slot001
  .line 9
    aload_1 ; met002_slot001
    ldc "Hello, invokedynamic!"
    invokeinterface java.util.function.Consumer.accept(java.lang.Object)void 2
  .line 10
    return


;met002_slot001                                ; DATA XREF: main+13↑w ...
  .end method

; ---------------------------------------------------------------------------

