;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                 HexRays                                 |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 3C19E7131DACF2B6A4226FD2EF3C431FE6F16425CEBE483FF14164820F8016D5
; Input MD5    : 8A4E87E36C2207FC7F84716C1F52E40B
; Input CRC32  : 114FFA7F

; File Name   : /home/austin/Github/Decompiler-Kotlin/Test5.class
; Format      : JavaVM Class File (JDK 1.8)

;Java Virtual Machine (JDK 1.8)

.bytecode 52.0
.source "Test5.java"

; ---------------------------------------------------------------------------


; Importing prototypes

;.import java.lang.Object                      ; DATA XREF: Test5↓i
;  java.lang.Object.<init>()void               ; CODE XREF: <init>+1↓P
;.import java.lang.ArithmeticException         ; DATA XREF: main+12↓i ...
;  java.lang.ArithmeticException.<init>(java.lang.String)void
                                               ; CODE XREF: main+18↓P
;  java.lang.ArithmeticException.getMessage()java.lang.String
                                               ; CODE XREF: main+67↓P
;.import java.lang.System
;  java.lang.System.out java.io.PrintStream    ; DATA XREF: main:met002_22↓r ...
;.import java.lang.StringBuilder               ; DATA XREF: main+25↓i ...
;  java.lang.StringBuilder.<init>()void        ; CODE XREF: main+29↓P ...
;  java.lang.StringBuilder.append(java.lang.String)java.lang.StringBuilder
                                               ; CODE XREF: main+34↓P ...
;  java.lang.StringBuilder.append(int)java.lang.StringBuilder
                                               ; CODE XREF: main+38↓P
;  java.lang.StringBuilder.toString()java.lang.String ; CODE XREF: main+41↓P ...
;.import java.io.PrintStream
;  java.io.PrintStream.println(java.lang.String)void ; CODE XREF: main+44↓P ...

; ---------------------------------------------------------------------------


.class public Test5
.super java.lang.Object


; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public <init>
  .limit stack 1
  .limit locals 1
  .line 1
    aload_0 ; met001_slot000
    invokespecial java.lang.Object.<init>()void
    return


;met001_slot000                                ; DATA XREF: <init>↑r
  .end method

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public static main
  .limit stack 3
  .limit locals 3
  .line 3
    iconst_0
    istore_1 ; met002_slot001

met002_2:                                      ; CODE XREF: main+82↓j
    .stack use locals
      locals Integer
    .end stack
    iload_1 ; met002_slot001
    iconst_5
    if_icmpge met002_85
  .line 5

met002_7:                                      ; DATA XREF: main+86↓i
    iload_1 ; met002_slot001
    iconst_3
    if_icmpne met002_22
  .line 6
    new java.lang.ArithmeticException
    dup
    ldc "Error occurred at i = 3"
    invokespecial java.lang.ArithmeticException.<init>(java.lang.String)void
    athrow
  .line 8

met002_22:                                     ; CODE XREF: main+9↑j
    .stack use locals
    .end stack
    getstatic java.lang.System.out java.io.PrintStream
    new java.lang.StringBuilder
    dup
    invokespecial java.lang.StringBuilder.<init>()void
    ldc "Iteration "
    invokevirtual java.lang.StringBuilder.append(java.lang.String)java.lang.StringBuilder
    iload_1 ; met002_slot001
    invokevirtual java.lang.StringBuilder.append(int)java.lang.StringBuilder
    invokevirtual java.lang.StringBuilder.toString()java.lang.String
    invokevirtual java.io.PrintStream.println(java.lang.String)void
  .line 11

met002_47:                                     ; DATA XREF: main+86↓i
    goto met002_79
  .line 9

met002_50:                                     ; DATA XREF: main+86↓i
    .stack use locals
      stack Object java.lang.ArithmeticException
    .end stack
    astore_2 ; met002_slot002
  .line 10
    getstatic java.lang.System.out java.io.PrintStream
    new java.lang.StringBuilder
    dup
    invokespecial java.lang.StringBuilder.<init>()void
    ldc "Caught exception: "
    invokevirtual java.lang.StringBuilder.append(java.lang.String)java.lang.StringBuilder
    aload_2 ; met002_slot002
    invokevirtual java.lang.ArithmeticException.getMessage()java.lang.String
    invokevirtual java.lang.StringBuilder.append(java.lang.String)java.lang.StringBuilder
    invokevirtual java.lang.StringBuilder.toString()java.lang.String
    invokevirtual java.io.PrintStream.println(java.lang.String)void
  .line 3

met002_79:                                     ; CODE XREF: main:met002_47↑j
    .stack use locals
    .end stack
    iinc 1 1
    goto met002_2
  .line 13

met002_85:                                     ; CODE XREF: main+4↑j
    .stack
    .end stack
    return

    .catch java.lang.ArithmeticException from met002_7 to met002_47 using met002_50



;met002_slot001                                ; DATA XREF: main+1↑w ...
;met002_slot002                                ; DATA XREF: main:met002_50↑w ...
  .end method

; ---------------------------------------------------------------------------

