;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                 HexRays                                 |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : B50B2D944E23BFCBE57F9316D9C3ACE12DE3AD16CC40979804AA6E8B3C7E7C2C
; Input MD5    : ED32F5DD24028DDA621CB721407BD5B5
; Input CRC32  : E93E5673

; File Name   : /home/austin/Github/Decompiler-Kotlin/Test2.class
; Format      : JavaVM Class File (JDK 1.8)

;Java Virtual Machine (JDK 1.8)

.bytecode 52.0
.source "Test2.java"

; ---------------------------------------------------------------------------


; Importing prototypes

;.import java.lang.Object                      ; DATA XREF: Test2↓i
;  java.lang.Object.<init>()void               ; CODE XREF: <init>+1↓P
;.import java.lang.System
;  java.lang.System.out java.io.PrintStream    ; DATA XREF: hello↓r ...
;.import java.io.PrintStream
;  java.io.PrintStream.println(java.lang.String)void ; CODE XREF: hello+5↓P
;  java.io.PrintStream.println(int)void        ; CODE XREF: main+13↓P ...

; ---------------------------------------------------------------------------


.class public Test2
.super java.lang.Object


; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public <init>
  .limit stack 1
  .limit locals 1
  .line 1
    aload_0 ; met001_slot000
    invokespecial java.lang.Object.<init>()void
    return


;met001_slot000                                ; DATA XREF: <init>↑r
  .end method

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method static hello
  .limit stack 2
  .line 4
    getstatic java.lang.System.out java.io.PrintStream 
                                               ; CODE XREF: main:met003_26↓P
    ldc "HELLO"
    invokevirtual java.io.PrintStream.println(java.lang.String)void
  .line 5
    return
  .end method

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public static main
  .limit stack 2
  .limit locals 2
  .line 8
    iconst_0
    istore_1 ; met003_slot001
  .line 9
    iload_1 ; met003_slot001
    ifne met003_19
  .line 10
    iinc 1 1
  .line 11
    getstatic java.lang.System.out java.io.PrintStream
    iload_1 ; met003_slot001
    invokevirtual java.io.PrintStream.println(int)void
    goto met003_26
  .line 13

met003_19:                                     ; CODE XREF: main+3↑j
    .stack use locals
      locals Integer
    .end stack
    getstatic java.lang.System.out java.io.PrintStream
    iload_1 ; met003_slot001
    invokevirtual java.io.PrintStream.println(int)void
  .line 16

met003_26:                                     ; CODE XREF: main+16↑j
    .stack use locals
    .end stack
    invokestatic Test2.hello()void
  .line 17
    return


;met003_slot001                                ; DATA XREF: main+1↑w ...
  .end method

; ---------------------------------------------------------------------------

