cc_library(
    name = "TitaniumDecompiler",
    hdrs = [
        "TitaniumDecompiler.h"
    ],
    deps = [
        "//TitaniumDecompiler/src/TitaniumDecompiler/Decompiler:decompiler",
        "//TitaniumDecompiler/src/Disassembler:jvm_disassembler_provider",
        "//TitaniumDecompiler/src/FileFormats/JVM:jvm_format",
        "//TitaniumDecompiler/src/Core:core",
    ],
    copts = [
        "-ITitaniumDecompiler/src",
    ],
    visibility = [
        "//TitaniumApplication/src:__subpackages__",
        "//TitaniumTests/TitaniumDecompilerTests:__subpackages__",
    ],
)
