#pragma once

#include <string>

// Class access
#define ACC_PUBLIC 0x0001      // Declared public
#define ACC_FINAL 0x0010       // Declared final
#define ACC_SUPER 0x0020       // Tread superclass methods specially when invoked by the invokespecial instruction
#define ACC_INTERFACE 0x0200   // Is an interface, not a class
#define ACC_ABSTRACT 0x0400    // Declared abstract; must not be instantiated
#define ACC_SYNTHETIC 0x1000   // Declared synthetic; not present in the source code
#define ACC_ANNOTATION 0x2000  // Declared as an annotation type
#define ACC_ENUM 0x4000        // Declared as an enum type

// Field access (Additional)
#define ACC_PRIVATE 0x0002    // Declared private
#define ACC_PROTECTED 0x0004  // Declared protected
#define ACC_STATIC 0x0008     // Declared static
#define ACC_VOLATILE 0x0040   // Declared volatile; cannot be cached
#define ACC_TRANSIENT 0x0080  // Declared transient

// Method access (additional)
#define ACC_SYNCHRONIZED 0x0020  // Declared synchronized; invocation is wrapped by a monitor use
#define ACC_BRIDGE 0x0040        // A bridge method, generated by the compiler
#define ACC_VARARGS 0x0080       // Declared with variable number of arguments
#define ACC_NATIVE 0x0100        // Declared native; implemented in a language other than Java
#define ACC_STRICT 0x0800        // Declared strictfp; floating-point mode is FP-strict

// Parameter access (additional)
#define ACC_MANDATED 0x8000

#define ACC_ACCESS_MASK (ACC_PUBLIC | ACC_PROTECTED | ACC_PRIVATE)
#define ACC_CLASS (ACC_PUBLIC | ACC_FINAL | ACC_SUPER | ACC_INTERFACE | ACC_ABSTRACT | ACC_SYNTHETIC | ACC_ANNOTATION | ACC_ENUM)
#define ACC_NESTED_CLASS \
    (ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED | ACC_STATIC | ACC_FINAL | ACC_INTERFACE | ACC_ABSTRACT | ACC_SYNTHETIC | ACC_ANNOTATION | ACC_ENUM)
#define ACC_FIELD (ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED | ACC_STATIC | ACC_FINAL | ACC_VOLATILE | ACC_TRANSIENT | ACC_SYNTHETIC | ACC_ENUM)
#define ACC_METHOD                                                                                                                                 \
    (ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED | ACC_STATIC | ACC_FINAL | ACC_SYNCHRONIZED | ACC_BRIDGE | ACC_VARARGS | ACC_NATIVE | ACC_ABSTRACT | \
     ACC_STRICT | ACC_SYNTHETIC)
#define ACC_PARAMETER (ACC_FINAL | ACC_SYNTHETIC | ACC_MANDATED)

namespace TitaniumDecompiler {
std::string ParseJavaClassAccessFlag(int access);
std::string ParseJavaFieldAccessFlag(int access);
std::string ParseJavaMethodsAccessFlag(int access);
}  // namespace TitaniumDecompiler