load("@rules_cc//cc:defs.bzl", "cc_library", "objc_library")

cc_library(
    name = "jvm_format",
    srcs = [
        "AccessFlags.cpp",
        "AttributeInnerStructures.cpp",
        "Attributes.cpp",
        "AttributeStructures.cpp",
        "ClassFileParser.cpp",
        "ClassFile.cpp",
        "ConstantPool.cpp",
        "ConstInfoPool.cpp",
        "Fields.cpp",
        "Instruction.cpp",
        "JarFile.cpp",
        "Methods.cpp",
        "StackMapFrame.cpp",
        "VerificationTypeInfo.cpp",
        "JVMFormatParser.cpp",
    ],
    hdrs = [
        "AccessFlags.h",
        "AttributeInnerStructures.h",
        "Attributes.h",
        "AttributeStructures.h",
        "ClassFileParser.h",
        "ClassFile.h",
        "CodeConstants.h",
        "ConstantPool.h",
        "ConstPoolInfo.h",
        "Fields.h",
        "Instruction.h",
        "JarFile.h",
        "Methods.h",
        "StackMapFrame.h",
        "VerificationTypeInfo.h",
        "JVMFormatParser.h",
    ],
    visibility = [
        "//:__pkg__",
        "//TitaniumDecompiler/src:__subpackages__",
    ],
    includes = ["//TitaniumDecompiler/src"],
    # strip_include_prefix = "//TitaniumDecompiler/src",
    copts = [
        "-ITitaniumDecompiler/src",
        "-ITitaniumLogger/src",
    ],
    deps = [
        "//TitaniumDecompiler/src/Utils:utils",
        "//TitaniumDecompiler/src/Core:headers",
        "//TitaniumLogger/src/TitaniumLogger/Logger:titanium_logger",
    ],
)
cc_library(
    name = "platform_jvm_test",
    srcs = [
        "AccessFlags.cpp",
        "AttributeInnerStructures.cpp",
        "Attributes.cpp",
        "AttributeStructures.cpp",
        "ClassFileParser.cpp",
        "ConstantPool.cpp",
        "ConstInfoPool.cpp",
        "Fields.cpp",
        "Instruction.cpp",
        "JarFile.cpp",
        "Methods.cpp",
        "StackMapFrame.cpp",
        "VerificationTypeInfo.cpp",
    ],
    hdrs = [
        "AccessFlags.h",
        "AttributeInnerStructures.h",
        "Attributes.h",
        "AttributeStructures.h",
        "ClassFileParser.h",
        "CodeConstants.h",
        "ConstantPool.h",
        "ConstPoolInfo.h",
        "Fields.h",
        "Instruction.h",
        "JarFile.h",
        "Methods.h",
        "StackMapFrame.h",
        "VerificationTypeInfo.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    includes = ["//TitaniumDecompiler/src"],
    # strip_include_prefix = "//TitaniumDecompiler/src",
    copts = [
        "-ITitaniumDecompiler/src",
        "-ITitaniumLogger/src",
    ],
    deps = [
        "//TitaniumDecompiler/src/Utils:utils",
        "//TitaniumLogger/src/TitaniumLogger/Logger:titanium_logger",
    ],
)
