load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")

cc_test(
    name = "class_file_parser_test",
    size = "small",
    srcs = ["ClassFileParserTest.cpp"],
    copts = [
        "-ITitaniumDecompiler/src",
    ],
    data = [
        "//JavaTestFiles:test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "disassembler_test",
    size = "small",
    srcs = ["DisassemblerTest.cpp"],
    copts = ["-ITitaniumDecompiler/src"],
    data = [
        "//JavaTestFiles:Test.class",
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumDecompiler/src/Core/Disassembly:disassembly",
        "//TitaniumDecompiler/src/FileFormats/JVM:platform_jvm_test",
        "//TitaniumDecompiler/src/TitaniumDecompiler/Disassembler:disassembler_test",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "jvm_disassembler_test",
    size = "small",
    srcs = ["JVMDisassemblerTest.cpp"],
    copts = ["-ITitaniumDecompiler/src"],
    data = [
        "//JavaTestFiles:Test.class",
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumDecompiler/src/FileFormats/JVM:platform_jvm_test",
        "//TitaniumDecompiler/src/TitaniumDecompiler/Disassembler:disassembler_test",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "jar_file_parser_test",
    size = "small",
    srcs = ["JarFileTest.cpp"],
    copts = [
        "-ITitaniumDecompiler/src",
    ],
    data = [
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "function_test",
    size = "small",
    srcs = ["FunctionTest.cpp"],
    copts = [
        "-ITitaniumDecompiler/src",
    ],
    data = [
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "exception_range_test",
    size = "small",
    srcs = ["ExceptionRangeCFGTest.cpp"],
    copts = [
        "-ITitaniumDecompiler/src",
    ],
    data = [
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "common_ops_test",
    size = "small",
    srcs = ["CommonOpsTest.cpp"],
    copts = [
        "-ITitaniumDecompiler/src",
    ],
    data = [
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "basic_block_test",
    size = "small",
    srcs = ["BasicBlockTest.cpp"],
    copts = ["-ITitaniumDecompiler/src"],
    data = [
        "//JavaTestFiles:Test.class",
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumDecompiler/src/FileFormats/JVM:platform_jvm_test",
        "//TitaniumDecompiler/src/TitaniumDecompiler/Disassembler:disassembler_test",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "access_flags_test",
    size = "small",
    srcs = ["AccessFlagsTest.cpp"],
    copts = ["-ITitaniumDecompiler/src"],
    data = [
        "//JavaTestFiles:Test.class",
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumDecompiler/src/FileFormats/JVM:platform_jvm_test",
        "//TitaniumDecompiler/src/TitaniumDecompiler/Disassembler:disassembler_test",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "attribute_inner_structure_test",
    size = "small",
    srcs = ["AttributeInnerStructuresTest.cpp"],
    copts = ["-ITitaniumDecompiler/src"],
    data = [
        "//JavaTestFiles:Test.class",
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumDecompiler/src/FileFormats/JVM:platform_jvm_test",
        "//TitaniumDecompiler/src/TitaniumDecompiler/Disassembler:disassembler_test",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "attributes_test",
    size = "small",
    srcs = ["AttributesTest.cpp"],
    copts = ["-ITitaniumDecompiler/src"],
    data = [
        "//JavaTestFiles:Test.class",
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumDecompiler/src/FileFormats/JVM:platform_jvm_test",
        "//TitaniumDecompiler/src/TitaniumDecompiler/Disassembler:disassembler_test",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "attribute_structures_test",
    size = "small",
    srcs = ["AttributeStructuresTest.cpp"],
    copts = ["-ITitaniumDecompiler/src"],
    data = [
        "//JavaTestFiles:Test.class",
        "//JavaTestFiles:TestJarFile/TestJarFile.jar",
        "//JavaTestFiles:jar_test_files",
    ],
    deps = [
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumDecompiler/src/FileFormats/JVM:platform_jvm_test",
        "//TitaniumDecompiler/src/TitaniumDecompiler/Disassembler:disassembler_test",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
