;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                 HexRays                                 |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : EECD6D6F69274E5EA0E1F482613537D8320D87668379054E8A05A2B86C7E7956
; Input MD5    : 8FF9F8013EAD1CCDD96A66CA0FC8975C
; Input CRC32  : 2AF968D9

; File Name   : /home/austin/test/Test.class
; Format      : JavaVM Class File (JDK 1.8)

;Java Virtual Machine (JDK 1.8)

.bytecode 52.0
.source "Test.java"

; ---------------------------------------------------------------------------


; Importing prototypes

;.import java.lang.Object                      ; DATA XREF: Test↓i
;  java.lang.Object.<init>()void               ; CODE XREF: <init>+1↓P
;.import java.lang.System
;  java.lang.System.out java.io.PrintStream    ; DATA XREF: main↓r
;.import java.io.PrintStream
;  java.io.PrintStream.println(java.lang.String)void ; CODE XREF: main+5↓P

; ---------------------------------------------------------------------------


.class public Test
.super java.lang.Object


; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public <init>
  .limit stack 1
  .limit locals 1
  .line 1
    aload_0 ; met001_slot000
    invokespecial java.lang.Object.<init>()void
    return


;met001_slot000                                ; DATA XREF: <init>↑r
  .end method

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public static main
  .limit stack 2
  .limit locals 1
  .line 2
    getstatic java.lang.System.out java.io.PrintStream
    ldc "Test"
    invokevirtual java.io.PrintStream.println(java.lang.String)void
    return


  .end method

; ---------------------------------------------------------------------------

