;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                                 HexRays                                 |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 1D2D9644BAFC48D297D705BF4019F450350AE971BEC2C7D327F93429BD464DB8
; Input MD5    : E777E07ADFE32024AA60C31AB81F165C
; Input CRC32  : 5D972CF1

; File Name   : /home/austin/Github/Decompiler-Kotlin/Test3.class
; Format      : JavaVM Class File (JDK 1.8)

;Java Virtual Machine (JDK 1.8)

.bytecode 52.0
.source "Test3.java"

; ---------------------------------------------------------------------------


; Importing prototypes

;.import java.lang.Object
;  java.lang.Object.<init>()void
;.import java.lang.System
;  java.lang.System.out java.io.PrintStream
;.import java.io.PrintStream
;  java.io.PrintStream.println(java.lang.String)void
;  java.io.PrintStream.println(int)void
;.import Test3$Inner

; ---------------------------------------------------------------------------


.class public Test3
.super java.lang.Object

  .inner class Inner inner Test3$Inner outer Test3

  .field public static final DICK int = 5

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public <init>
  .limit stack 1
  .limit locals 1
  .line 1
    aload_0 ; met001_slot000
    invokespecial java.lang.Object.<init>()void
    return


;met001_slot000
  .end method

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method static hello
  .limit stack 2
  .line 5
    getstatic java.lang.System.out java.io.PrintStream
    ldc "HELLO"
    invokevirtual java.io.PrintStream.println(java.lang.String)void
  .line 6
    return
  .end method

; ---------------------------------------------------------------------------


; Segment type: Pure code
  .method public static main
  .limit stack 2
  .limit locals 2
  .line 9
    iconst_0
    istore_1 ; met003_slot001
  .line 10
    iload_1 ; met003_slot001
    ifne met003_19
  .line 11
    iinc 1 1
  .line 12
    getstatic java.lang.System.out java.io.PrintStream
    iload_1 ; met003_slot001
    invokevirtual java.io.PrintStream.println(int)void
    goto met003_26
  .line 14

met003_19:
    .stack use locals
      locals Integer
    .end stack
    getstatic java.lang.System.out java.io.PrintStream
    iload_1 ; met003_slot001
    invokevirtual java.io.PrintStream.println(int)void
  .line 17

met003_26:
    .stack use locals
    .end stack
    invokestatic Test3.hello()void
  .line 18
    return


;met003_slot001
  .end method

; ---------------------------------------------------------------------------

