load("@rules_cc//cc:defs.bzl", "cc_library", "objc_library")

cc_library(
    name = "kernel",
    srcs = [
        "Loader.cpp",
    ],
    hdrs = [
        "Loader.h",
    ],
    visibility = [
        "//:__pkg__",
        "//TitaniumDecompiler/src:__subpackages__",
    ],
    deps = [
        "//TitaniumDecompiler/src/FileFormats/JVM:jvm_format",
    ],
    copts = [
        "-ITitaniumDecompiler/src",
    ],
    # strip_include_prefix = "//TitaniumDecompiler/src",
)
