load("@rules_cc//cc:defs.bzl", "cc_library", "objc_library")

cc_library(
    name = "panels",
    srcs = [
        "ConsolePanel.cpp",
        "DecompilerViewerPanel.cpp",
        "DisassemblyViewerPanel.cpp",
        "FunctionListingPanel.cpp",
        "HexViewerPanel.cpp",
        "SectionsPanel.cpp",
        "GraphViewPanel.cpp",
    ],
    hdrs = [
        "ConsolePanel.h",
        "ConsoleSink.h",
        "DecompilerViewerPanel.h",
        "DisassemblyViewerPanel.h",
        "FunctionListingPanel.h",
        "HexViewerPanel.h",
        "SectionsPanel.h",
        "GraphViewPanel.h",
    ],
    visibility = [
        "//:__pkg__",
        "//TitaniumApplication/src:__subpackages__",
    ],
    copts = [
        "-ITitaniumDecompiler/src",
        "-ITitaniumRenderer/src",
        "-ITitaniumLogger/src",
    ],
    deps = [
        "@imguilib//:imgui",
        "//TitaniumApplication/src/UI:ui",
        "//TitaniumRenderer/src:TitaniumRenderer",
        "//TitaniumDecompiler/src:TitaniumDecompiler",
        "//TitaniumLogger/src/TitaniumLogger/Logger:titanium_logger",
    ],
    linkstatic = 1,
)
