cc_library(
    name = "titanium_renderer_imgui",
    srcs = [
        "ImGuiBuild.cpp",
        "ImGuiLayer.cpp",
    ],
    deps = [
        ":headers",
        "//TitaniumRenderer/src/TitaniumRenderer/Core:headers",
        "//TitaniumRenderer/src/TitaniumRenderer/Renderer:headers",
        "//TitaniumRenderer/src/TitaniumRenderer/UI:ui",
        "@GLFW//:glfw",
        "@imguilib//:imgui",
        "@spdloglib//:spdlog",
    ] + select({
      "@platforms//os:macos": [

      ],
      "//conditions:default": [
        "@GLAD//:glad",
      ],
    }),
    defines = select({
      "@platforms//os:macos": [
        "TD_PLATFORM_MACOS"
      ],
      "//conditions:default": [],
    }),
    copts = [
        "-ITitaniumRenderer/src"
    ],
    visibility = [
        "//TitaniumRenderer/src:__subpackages__",
    ],
)

cc_library(
    name = "headers",
    hdrs = [
        "ImGuiLayer.h",
        "ImGuiRenderer.h",
    ],
    deps = [
        # "//TitaniumRenderer/src/TitaniumRenderer/Core:headers",
    ],
    copts = [
        "-ITitaniumRenderer/src"
    ],
    # strip_include_prefix = "//TitaniumRenderer/src",
    visibility = [
        "//TitaniumRenderer/src:__subpackages__",
    ],
)
