cc_library(
    name = "titanium_renderer_imgui",
    srcs = [
        "ImGuiBuild.cpp",
        "ImGuiLayer.cpp",
        "ImGuiRenderer.cpp",
    ],
    copts = [
        "-ITitaniumRenderer/src",
    ],
    defines = select({
        "@platforms//os:macos": [
            "TD_PLATFORM_MACOS",
        ],
        "//conditions:default": [],
    }),
    visibility = [
        "//TitaniumRenderer/src:__subpackages__",
    ],
    deps = [
        ":headers",
        "//TitaniumRenderer/src/TitaniumRenderer/Core:headers",
        "//TitaniumRenderer/src/TitaniumRenderer/Renderer:headers",
        "//TitaniumRenderer/src/TitaniumRenderer/UI:ui",
        "@GLFW//:glfw",
        "@imguilib//:imgui",
        "@spdloglib//:spdlog",
    ] + select({
        "@platforms//os:macos": [
            "//TitaniumRenderer/src/Platform/Metal:titanium_renderer_platform_metal",
        ],
        "//conditions:default": [
            "//TitaniumRenderer/src/Platform/OpenGL:titanium_renderer_platform_opengl",
            "@GLAD//:glad",
        ],
    }),
)

cc_library(
    name = "headers",
    hdrs = [
        "ImGuiLayer.h",
        "ImGuiRenderer.h",
    ],
    copts = [
        "-ITitaniumRenderer/src",
    ],
    # strip_include_prefix = "//TitaniumRenderer/src",
    visibility = [
        "//TitaniumRenderer/src:__subpackages__",
    ],
    deps = [
        # "//TitaniumRenderer/src/TitaniumRenderer/Core:headers",
    ],
)
